import React from 'react'
import ResponsiveTable from './index'

export default {
  title: 'ResponsiveTable',
}

const data = [
  {
    id: 0,
    title: 'Pirelli',
    subtitle: 'P Zero',
    summer: true,
    type: '205/55/R16',
    number: 82,
    letter: 'T',
    fuel: 'g',
    rain: 'e',
    sound: 73,
    oldPrice: 475.0,
    newPrice: 475.0,
    pieceNumber: 4,
    vat: 20.33,
    amount: 2,
  },
  {
    id: 3,
    title: 'Pirelli',
    subtitle: 'P Zero',
    summer: true,
    type: '205/55/R16',
    number: 82,
    letter: 'T',
    fuel: 'g',
    rain: 'e',
    sound: 73,
    oldPrice: 475.0,
    newPrice: 475.0,
    pieceNumber: 4,
    vat: 20.33,
    amount: 2,
  },
  {
    id: 4,
    title: 'Pirelli',
    subtitle: 'P Zero',
    summer: true,
    type: '205/55/R16',
    number: 82,
    letter: 'T',
    fuel: 'g',
    rain: 'e',
    sound: 73,
    oldPrice: 475.0,
    newPrice: 475.0,
    pieceNumber: 4,
    vat: 20.33,
    amount: 2,
  },
  {
    id: 5,
    title: 'Pirelli',
    subtitle: 'P Zero',
    summer: true,
    type: '205/55/R16',
    number: 82,
    letter: 'T',
    fuel: 'g',
    rain: 'e',
    sound: 73,
    oldPrice: 475.0,
    newPrice: 475.0,
    pieceNumber: 4,
    vat: 20.33,
    amount: 2,
  },
  {
    id: 6,
    title: 'Pirelli',
    subtitle: 'P Zero',
    summer: true,
    type: '205/55/R16',
    number: 82,
    letter: 'T',
    fuel: 'g',
    rain: 'e',
    sound: 73,
    oldPrice: 475.0,
    newPrice: 475.0,
    pieceNumber: 4,
    vat: 20.33,
    amount: 2,
  },
  {
    id: 7,
    title: 'Pirelli',
    subtitle: 'P Zero',
    summer: true,
    type: '205/55/R16',
    number: 82,
    letter: 'T',
    fuel: 'g',
    rain: 'e',
    sound: 73,
    oldPrice: 475.0,
    newPrice: 475.0,
    pieceNumber: 4,
    vat: 20.33,
    amount: 2,
  },
  {
    id: 8,
    title: 'Pirelli',
    subtitle: 'P Zero',
    summer: true,
    type: '205/55/R16',
    number: 82,
    letter: 'T',
    fuel: 'g',
    rain: 'e',
    sound: 73,
    oldPrice: 475.0,
    newPrice: 475.0,
    pieceNumber: 4,
    vat: 20.33,
    amount: 2,
  },
  {
    id: 9,
    title: 'Pirelli',
    subtitle: 'P Zero',
    summer: true,
    type: '205/55/R16',
    number: 82,
    letter: 'T',
    fuel: 'g',
    rain: 'e',
    sound: 73,
    oldPrice: 475.0,
    newPrice: 475.0,
    pieceNumber: 4,
    vat: 20.33,
    amount: 2,
  },
  {
    id: 10,
    title: 'Pirelli',
    subtitle: 'P Zero',
    summer: true,
    type: '205/55/R16',
    number: 82,
    letter: 'T',
    fuel: 'g',
    rain: 'e',
    sound: 73,
    oldPrice: 475.0,
    newPrice: 475.0,
    pieceNumber: 4,
    vat: 20.33,
    amount: 2,
  },
]

const header = [
  'Product',
  'Quantity',
  'Unit price exclusive of VAT',
  'VAT Amount',
  'Total without VAT',
  'Total with VAT',
  'Remove',
]

export const DefaultView = () => (
  <ResponsiveTable header={header} data={data} onRemove={(value) => console.log(value)}></ResponsiveTable>
)

export const withError = () => <ResponsiveTable error errorText="The Table is empty" />
